# Generated by Django 6.0.1 on 2026-05-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiels',
            old_name='description_incident_materiel',
            new_name='solution_incident_materiel',
        ),
        migrations.RenameField(
            model_name='reseau',
            old_name='description_incident_reseau',
            new_name='solution_incident_reseau',
        ),
        migrations.RenameField(
            model_name='systeme',
            old_name='description_incident_système',
            new_name='solution_incident_système',
        ),
    ]
