# Generated by Django 6.0.1 on 2026-05-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_rename_description_incident_materiel_materiels_solution_incident_materiel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systeme',
            old_name='titre_système',
            new_name='titre_systeme',
        ),
    ]
