# Generated by Django 6.0.1 on 2026-05-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_rename_titre_système_systeme_titre_systeme'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiels',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AddField(
            model_name='reseau',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterModelTable(
            name='materiels',
            table='Incident_materiels',
        ),
        migrations.AlterModelTable(
            name='reseau',
            table='Incident_reseau',
        ),
    ]
