# Generated by Django 6.0.1 on 2026-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_materiels_user_reseau_user_alter_materiels_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiels',
            name='titre_incident',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
