# Generated by Django 6.0.1 on 2026-05-20 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_materiels_titre_incident'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSurvenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_incident', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('systeme', 'Système'), ('materiel', 'Matériel'), ('reseau', 'Réseau')], max_length=20)),
                ('solutionPrise', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'IncidentSurvenu',
            },
        ),
    ]
