# Generated by Django 6.0.1 on 2026-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentsurvenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsurvenu',
            name='description_incident',
            field=models.TextField(blank=True, null=True),
        ),
    ]
