# Generated by Django 6.0.1 on 2026-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_incidentsurvenu_description_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiels',
            name='fichier_solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/', verbose_name='Fichier solution'),
        ),
        migrations.AddField(
            model_name='reseau',
            name='fichier_solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/', verbose_name='Fichier solution'),
        ),
        migrations.AddField(
            model_name='systeme',
            name='fichier_solution',
            field=models.FileField(blank=True, null=True, upload_to='solution/', verbose_name='Fichier solution'),
        ),
    ]
