# Generated by Django 6.0.1 on 2026-04-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrapport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournal',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='rapports/'),
        ),
    ]
