# Generated by Django 6.0.1 on 2026-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrapport', '0002_rapportjournal_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportjournal',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rapportjournal',
            name='cci',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rapportjournal',
            name='email_destiny',
            field=models.TextField(verbose_name='Destinataires'),
        ),
    ]
