# Generated by Django 6.0.1 on 2026-04-22 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrapport', '0003_rapportjournal_cc_rapportjournal_cci_and_more'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalLu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='myrapport.rapportjournal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'RapportJournalLu',
                'unique_together': {('rapport', 'user')},
            },
        ),
    ]
