# Generated by Django 6.0.1 on 2026-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrapport', '0004_rapportjournallu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournal',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportjournal',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
