# Generated by Django 6.0.1 on 2026-05-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrapport', '0006_textmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='textmodel',
            table='Modele',
        ),
    ]
