# Generated by Django 6.0.1 on 2026-03-27 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('tech', 'Technicien')], default='tech', max_length=20, verbose_name='Rôle')),
                ('password', models.CharField(max_length=128)),
                ('statut', models.BooleanField(default=True, verbose_name='Statut du compte')),
                ('actif', models.BooleanField(default=False, verbose_name='En ligne')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
