# Generated by Django 6.0.1 on 2026-04-15 10:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=13, validators=[users.models.validate_phone], verbose_name='Téléphone'),
        ),
    ]
