# Generated by Django 6.0.1 on 2026-08-28 10:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20, validators=[users.models.validate_phone], verbose_name='Téléphone'),
        ),
    ]
