# Generated by Django 6.0.1 on 2026-03-27 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consommables', '0001_initial'),
        ('myrapport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boxOp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BoxOp',
            },
        ),
        migrations.CreateModel(
            name='BoxPaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boxPaf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BoxPaf',
            },
        ),
        migrations.CreateModel(
            name='Bobine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bobine', models.CharField(max_length=100)),
                ('debut_serie', models.IntegerField()),
                ('fin_serie', models.IntegerField()),
                ('est_terminee', models.BooleanField(default=False)),
                ('date_assignation', models.DateTimeField(default=django.utils.timezone.now)),
                ('consommable', models.ForeignKey(limit_choices_to={'type': 'etiquette'}, on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable')),
                ('box_paf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_consommables.boxpaf')),
            ],
            options={
                'db_table': 'Bobine',
            },
        ),
        migrations.CreateModel(
            name='Imprimante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_copie', models.IntegerField()),
                ('date_prise', models.DateTimeField(default=django.utils.timezone.now)),
                ('boxOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_consommables.boxop')),
            ],
            options={
                'db_table': 'Imprimante',
            },
        ),
        migrations.CreateModel(
            name='RapportBobine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bobine', models.CharField(max_length=100)),
                ('debut_serie', models.IntegerField()),
                ('fin_serie', models.IntegerField()),
                ('est_terminee', models.BooleanField()),
                ('box_paf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_consommables.boxpaf')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bobines', to='myrapport.rapportjournal')),
            ],
            options={
                'db_table': 'RapportBobine',
            },
        ),
        migrations.CreateModel(
            name='RapportImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_copie', models.IntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_consommables.boxop')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='myrapport.rapportjournal')),
            ],
            options={
                'db_table': 'RapportImpression',
            },
        ),
        migrations.CreateModel(
            name='RapportStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_entree', models.IntegerField()),
                ('qte_sortie', models.IntegerField()),
                ('qte_restant', models.IntegerField()),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrapport.rapportjournal')),
            ],
            options={
                'db_table': 'RapportStock',
            },
        ),
        migrations.CreateModel(
            name='RapportVignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_debut', models.IntegerField()),
                ('num_fin', models.IntegerField()),
                ('nb_abime', models.IntegerField()),
                ('box_paf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_consommables.boxpaf')),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='myrapport.rapportjournal')),
            ],
            options={
                'db_table': 'RapportVignette',
            },
        ),
        migrations.CreateModel(
            name='Stock_consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_entree', models.IntegerField()),
                ('qte_sortie', models.IntegerField()),
                ('qte_restant', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable')),
            ],
            options={
                'db_table': 'Stock_consommable',
            },
        ),
        migrations.CreateModel(
            name='Vignettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_debutVignette', models.IntegerField()),
                ('num_FinVignette', models.IntegerField()),
                ('nb_abime', models.IntegerField()),
                ('cause', models.CharField(blank=True, max_length=255)),
                ('date_modif', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_bobine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vignettes', to='stock_consommables.bobine')),
            ],
            options={
                'db_table': 'Vignette',
            },
        ),
    ]
