# Generated by Django 6.0.1 on 2026-03-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommables', '0002_remove_consommable_user'),
        ('stock_consommables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobine',
            name='consommable',
            field=models.ForeignKey(limit_choices_to={'type_consommable': 'Bobine'}, on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable'),
        ),
        migrations.AlterField(
            model_name='bobine',
            name='debut_serie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bobine',
            name='fin_serie',
            field=models.BigIntegerField(),
        ),
    ]
