# Generated by Django 6.0.1 on 2026-03-31 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommables', '0002_remove_consommable_user'),
        ('stock_consommables', '0002_alter_bobine_consommable_alter_bobine_debut_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobine',
            name='date_modif',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='bobine',
            constraint=models.UniqueConstraint(condition=models.Q(('est_terminee', False)), fields=('box_paf',), name='unique_active_bobine_par_box'),
        ),
    ]
