# Generated by Django 6.0.1 on 2026-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_consommables', '0003_bobine_date_modif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportbobine',
            name='debut_serie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportbobine',
            name='fin_serie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportvignette',
            name='num_debut',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='rapportvignette',
            name='num_fin',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vignettes',
            name='num_FinVignette',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vignettes',
            name='num_debutVignette',
            field=models.BigIntegerField(),
        ),
    ]
