# Generated by Django 6.0.1 on 2026-05-06 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_consommables', '0004_alter_rapportbobine_debut_serie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouleurEncre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('reserve', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CouleurEncre',
            },
        ),
        migrations.CreateModel(
            name='NiveauEncre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(100, 'Plein'), (75, '75%'), (50, '50%'), (25, '25%'), (0, 'Vide')], default=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boxOp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_consommables.boxop')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_consommables.couleurencre')),
            ],
            options={
                'db_table': 'NiveauEncre',
                'unique_together': {('boxOp', 'couleur')},
            },
        ),
    ]
