# Generated by Django 6.0.1 on 2026-05-11 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_consommables', '0005_couleurencre_niveauencre'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_consommable',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user', verbose_name='Technicien'),
        ),
    ]
