# Generated by Django 6.0.1 on 2026-07-07 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommables', '0002_remove_consommable_user'),
        ('stock_consommables', '0006_stock_consommable_user'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_entree_bureau', models.IntegerField()),
                ('qte_envoye_bureau', models.IntegerField()),
                ('qte_restant_bureau', models.IntegerField()),
                ('nom_site', models.CharField(max_length=10)),
                ('date_mouvement_bureau', models.DateTimeField(default=django.utils.timezone.now)),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'Stock_Bureau',
            },
        ),
    ]
