# Generated by Django 6.0.1 on 2026-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_consommables', '0007_stockbureau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbureau',
            name='nom_site',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
