# Generated by Django 6.0.1 on 2026-07-08 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consommables', '0002_remove_consommable_user'),
        ('stock_consommables', '0008_alter_stockbureau_nom_site'),
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('admin_expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_envoyes', to='users.user')),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consommables.consommable')),
                ('stock_bureau_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock_consommables.stockbureau')),
                ('tech_receveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus', to='users.user')),
            ],
            options={
                'db_table': 'Transfert_Stock',
            },
        ),
    ]
