# Generated by Django 6.0.1 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_consommables', '0009_transfertstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobine',
            name='numero_bobine',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='boxop',
            name='numero_boxOp',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='boxpaf',
            name='numero_boxPaf',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='couleurencre',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
