# Generated by Django 6.0.1 on 2026-03-27 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_consommable', models.CharField(max_length=20, verbose_name='nom de consommable')),
                ('type_consommable', models.CharField(max_length=50, verbose_name='tyde de consommable')),
                ('mode_consommation', models.CharField(max_length=10, verbose_name='mode de consommation')),
                ('created_at_consommation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'consommable',
                'verbose_name_plural': 'consommables',
                'db_table': 'Consommable',
            },
        ),
    ]
