# Generated by Django 6.0.1 on 2026-03-27 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myrapport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('jour', models.FloatField()),
            ],
            options={
                'db_table': 'CategorieSejour',
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vol', models.CharField(max_length=50, unique=True)),
                ('date_arrivee_vol', models.DateTimeField()),
                ('date_fin_vol', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Vol',
            },
        ),
        migrations.CreateModel(
            name='RapportVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vol', models.CharField(max_length=50)),
                ('sejour', models.CharField(max_length=20)),
                ('nb_par_sejour', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vol', to='myrapport.rapportjournal')),
            ],
            options={
                'db_table': 'RapportVol',
            },
        ),
        migrations.CreateModel(
            name='Mouvement_vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_par_sejour', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mouvement_vol.categoriesejour')),
                ('num_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mouvement_vol.vol')),
            ],
            options={
                'db_table': 'Mouvement_vol',
            },
        ),
    ]
