# Generated by Django 6.0.1 on 2026-04-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement_vol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesejour',
            name='jour',
        ),
        migrations.AddField(
            model_name='categoriesejour',
            name='annotationVisa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoriesejour',
            name='libelle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
