# Generated by Django 6.0.1 on 2026-04-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement_vol', '0002_remove_categoriesejour_jour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesejour',
            old_name='annotationVisa',
            new_name='typeVisa',
        ),
    ]
