# Generated by Django 6.0.1 on 2026-04-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement_vol', '0003_rename_annotationvisa_categoriesejour_typevisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='numero_vol',
            field=models.CharField(max_length=50),
        ),
    ]
