# Generated by Django 6.0.1 on 2026-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouvement_vol', '0004_alter_vol_numero_vol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vol',
            name='numero_vol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
