# Generated by Django 6.0.1 on 2026-07-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_group', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'Groupe_inventaire',
            },
        ),
        migrations.CreateModel(
            name='ComposantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=100)),
                ('marque_materiel', models.CharField(max_length=100)),
                ('numero_serie', models.CharField()),
                ('configuration', models.CharField()),
                ('Etat_materiel', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.groupinventaire')),
            ],
            options={
                'db_table': 'Composant_groupe',
            },
        ),
    ]
