# Generated by Django 6.0.1 on 2026-07-13 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composantgroup',
            name='composant_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupinventaire',
            name='group_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
