# Generated by Django 6.0.1 on 2026-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_composantgroup_composant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinventaire',
            name='access_group',
            field=models.BooleanField(default=False),
        ),
    ]
