# Generated by Django 6.0.1 on 2026-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_composantgroup_test_fonctionnalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composantgroup',
            name='Etat_materiel',
            field=models.BooleanField(null=True),
        ),
    ]
