# Generated by Django 6.0.1 on 2026-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_alter_composantgroup_etat_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composantgroup',
            name='configuration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='composantgroup',
            name='numero_serie',
            field=models.CharField(max_length=100),
        ),
    ]
