# Generated by Django 6.0.1 on 2026-07-23 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_alter_composantgroup_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composantgroup',
            name='date_remplacement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composantgroup',
            name='lineage_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='composantgroup',
            name='remplace',
            field=models.ForeignKey(blank=True, help_text='Ancien matériel que cette ligne remplace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacant', to='inventaire.composantgroup'),
        ),
    ]
