# Generated by Django 6.0.1 on 2026-07-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_site_groupinventaire_site'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site',
            table='site',
        ),
    ]
