# Generated by Django 6.0.1 on 2026-09-07 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0009_alter_site_table'),
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='composantgroup',
            name='model_materiel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composantgroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
        migrations.AlterField(
            model_name='composantgroup',
            name='numero_serie',
            field=models.CharField(error_messages={'unique': 'Cette numéro de série existe déjà.'}, max_length=100, unique=True),
        ),
    ]
