# Generated by Django 6.0.1 on 2026-03-27 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails_destinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=20, verbose_name="nom du propriétaire de l'email")),
                ('emails_destiny', models.CharField(max_length=100, verbose_name='adresse email destinataire')),
                ('email_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de création de l'email")),
            ],
            options={
                'verbose_name': 'email_destinataire',
                'verbose_name_plural': 'emails_destinataires',
                'db_table': 'emails_destinataire',
            },
        ),
    ]
